version: "3.1"

services:
  map-editor-client:
    image: node:9
    working_dir: /src/map-editor/client
    command: npm start
    volumes:
      - ./src:/src/
    ports:
      - "8888:8080"

  map-editor-server:
    image: node:9
    working_dir: /src/map-editor/server
    command: npm start
    volumes:
      - ./src:/src/
    ports:
      - "8999:8999"
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root

  mongo:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/data/db