version: "3.1"

services:
  map-editor-client:
    image: node:9
    working_dir: /src/map-editor/client
    entrypoint: ./entrypoint.sh
    volumes:
      - ./src:/src/
    ports:
      - "8888:8080"

  map-editor-server:
    image: node:9
    working_dir: /src/map-editor/server
    entrypoint: ./entrypoint.sh
    volumes:
      - ./src:/src/
    ports:
      - "8999:8999"

  mongo:
    image: mongo:4.0
    restart: always
    volumes:
      - ./data/db:/data/db